# Countries Plugin Configuration
# Version: 1.0.0

# General Settings
general:
  # Enable debug mode for detailed logging
  enable-debug: false
  
  # Auto-save interval in seconds (300 = 5 minutes)
  auto-save-interval: 300
  
  # Maximum number of countries a player can own
  max-countries-per-player: 1
  
  # Maximum number of territories per country
  max-territories-per-country: 50
  
  # Default language for messages
  language: "en"

# Economy Settings
economy:
  # Starting balance for new players
  starting-balance: 1000.0
  
  # Tax collection interval in seconds (86400 = 24 hours)
  tax-collection-interval: 86400
  
  # Default tax rate (0.05 = 5%)
  default-tax-rate: 0.05
  
  # Maximum tax rate allowed (0.25 = 25%)
  max-tax-rate: 0.25
  
  # Enable integration with Vault economy
  use-vault: true
  
  # Currency symbol
  currency-symbol: "$"

# Territory Settings
territory:
  # Default claiming limits (can be overridden by permissions)
  default-max-chunks: 50
  default-max-territories: 5
  
  # Cost to claim a chunk
  chunk-claim-cost: 100.0
  
  # Maximum chunks per territory
  max-chunks-per-territory: 100
  
  # Allow claiming in wilderness (outside of countries)
  allow-wilderness-claims: true
  
  # Enable territory protection
  enable-protection: true
  
  # Show territory borders with particles
  show-borders: true
  
  # Territory upkeep cost per chunk per day
  upkeep-cost-per-chunk: 5.0
  
  # Advanced territory features
  enable-sub-areas: true
  enable-rental-system: true
  enable-territory-taxes: true
  enable-role-system: true
  
  # Sub-area limits
  max-sub-areas-per-territory: 10
  max-sub-area-size: 1000
  
  # Rental settings
  default-rent-duration: 30
  max-rent-price: 10000.0
  
  # Tax settings
  max-territory-tax-rate: 0.20
  tax-collection-interval: 86400
  
  # Particle border settings
  particles:
    enabled: true
    duration: 10
    min-height: 60
    max-height: 80

# Diplomacy Settings
diplomacy:
  # Cost to form an alliance
  alliance-cost: 5000.0
  
  # Cost to declare war
  war-declaration-cost: 10000.0
  
  # Enable trade agreements
  enable-trade: true
  
  # Maximum number of allies per country
  max-allies: 10

# Country Settings
country:
  # Minimum name length
  min-name-length: 3
  
  # Maximum name length
  max-name-length: 16
  
  # Cost to create a country
  creation-cost: 10000.0
  
  # Enable custom country flags
  enable-flags: true
  
  # Maximum number of citizens per country
  max-citizens: 100

# Law & Order Settings
law:
  # Enable law system
  enabled: true
  
  # Maximum fine amount
  max-fine-amount: 10000.0
  
  # Jail time multiplier (minutes per crime severity)
  jail-time-multiplier: 5
  
  # Enable bounty system
  enable-bounties: true

# GUI Settings
gui:
  # Enable GUI interfaces
  enabled: true
  
  # GUI update interval in ticks (20 = 1 second)
  update-interval: 20
  
  # Enable sound effects
  enable-sounds: true

# Database Settings
database:
  # Database type: sqlite, mysql
  type: "sqlite"
  
  # SQLite settings
  sqlite:
    filename: "countries.db"
    
  # Connection pool settings
  pool:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

# Performance Settings
performance:
  # Enable async operations
  async-operations: true
  
  # Cache size for countries
  country-cache-size: 1000
  
  # Cache size for territories
  territory-cache-size: 5000
  
  # Cache expiry time in minutes
  cache-expiry-minutes: 30